// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCalRC_kTis7sFS4TbJgpFdw02gfQw9zT0',
    appId: '1:603140255184:web:fb45d9192f7c7cd4f61dd5',
    messagingSenderId: '603140255184',
    projectId: 'utune-music',
    authDomain: 'utune-music.firebaseapp.com',
    storageBucket: 'utune-music.firebasestorage.app',
    measurementId: 'G-6G4WZLG3P0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFbT2e0E-6zuu6xHrjlOz58nMy8WdYTRI',
    appId: '1:603140255184:android:134e0751adaef349f61dd5',
    messagingSenderId: '603140255184',
    projectId: 'utune-music',
    storageBucket: 'utune-music.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZP_fZVVe4LCTevFO0ST3KjQWSaVJwkpY',
    appId: '1:603140255184:ios:6063d4c47bd463e5f61dd5',
    messagingSenderId: '603140255184',
    projectId: 'utune-music',
    storageBucket: 'utune-music.firebasestorage.app',
    iosBundleId: 'com.example.utune',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZP_fZVVe4LCTevFO0ST3KjQWSaVJwkpY',
    appId: '1:603140255184:ios:6063d4c47bd463e5f61dd5',
    messagingSenderId: '603140255184',
    projectId: 'utune-music',
    storageBucket: 'utune-music.firebasestorage.app',
    iosBundleId: 'com.example.utune',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCalRC_kTis7sFS4TbJgpFdw02gfQw9zT0',
    appId: '1:603140255184:web:bd864cb8e6c2a8c4f61dd5',
    messagingSenderId: '603140255184',
    projectId: 'utune-music',
    authDomain: 'utune-music.firebaseapp.com',
    storageBucket: 'utune-music.firebasestorage.app',
    measurementId: 'G-LR41GW45CX',
  );
}
